name: typ to pdf

on: push

jobs: 
  makePdf: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - run: typst compile main.typ main.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          path: main.pdf
