name: Compile Typst

on:
  push:
    paths:
      - '**.typ'
      - '.github/workflows/compile-typst.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Typst
      uses: typst-community/setup-typst@v3

    - name: Compile main.typ to PDF
      run: typst compile main.typ out/main.pdf
      uses: actions/upload-artifact@v4
      with:
        name: typst-pdf
        path: out/main.pdf
        overwrite: true
        compression-level: 0
