name: Compile and commit Typst document
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.pdf'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  compile_typst_and_commit:
    name: Compile typst to pdf and commit
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: setup typst
        uses: typst-community/setup-typst@v4
      - name: Compile Typst document
        run: typst compile main.typ out/main.pdf
      - name: Add and commit to main
        run: | 
          git config --global user.name 'Typst Compile Bot'
          git config --global user.email 'shubhssharma@proton.me'
          git add out/main.pdf
          git commit -m "[Bot] Update PDF"
          git push
